#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║              🚀 PORTNOX TOTAL COST ANALYZER - LAUNCH 🚀                       ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Platform is ready to launch!"
echo ""
echo "To run the platform:"
echo ""
echo "1. Using Python:"
echo "   python3 -m http.server 8000"
echo ""
echo "2. Using Node.js:"
echo "   npx serve"
echo ""
echo "3. Using PHP:"
echo "   php -S localhost:8000"
echo ""
echo "Then open http://localhost:8000 in your browser"
echo ""
echo "Features implemented:"
echo "✅ All 13 vendors with complete pricing"
echo "✅ All industries (15+) with specific requirements"
echo "✅ All compliance frameworks (20+) with NAC mappings"
echo "✅ Comprehensive risk and security analysis"
echo "✅ Cyber insurance impact calculations"
echo "✅ Enhanced vendor selection with pills"
echo "✅ Executive, Financial, Risk, Compliance, Operational views"
echo "✅ Interactive charts and visualizations"
echo "✅ Export functionality"
echo "✅ Fully responsive design"
echo ""
echo "Note: Add vendor logo PNG files to img/vendors/ for best experience"
