-- Insert vendor data
INSERT INTO vendors (id, name, category, pricing_model, base_cost, per_user_cost, setup_cost, annual_discount, features, compliance_certifications, security_features, integration_capabilities, support_tiers, deployment_options, scalability_limits, vendor_lock_in_risk, market_position, financial_stability, innovation_score, customer_satisfaction) VALUES
('portnox', 'Portnox', 'NAC', 'per_device', 15000, 25, 5000, 15, 
 '["Device Discovery", "Policy Enforcement", "Guest Access", "BYOD Support", "Network Segmentation", "Threat Detection", "Compliance Reporting", "API Integration"]',
 '["SOC 2", "ISO 27001", "HIPAA", "PCI DSS", "GDPR"]',
 '["Zero Trust Architecture", "Multi-factor Authentication", "Behavioral Analytics", "Threat Intelligence", "Encrypted Communications"]',
 '["REST API", "SIEM Integration", "Active Directory", "LDAP", "RADIUS", "Cloud Platforms"]',
 '["24/7 Support", "Professional Services", "Training", "Documentation"]',
 '["Cloud", "On-Premises", "Hybrid"]',
 '{"max_devices": 50000, "max_policies": 1000, "max_users": 10000}',
 'low', 'leader', 'stable', 9, 8.7),

('cisco-ise', 'Cisco ISE', 'NAC', 'per_device', 25000, 35, 8000, 12,
 '["Identity Services", "Policy Management", "Guest Portal", "BYOD", "Profiling", "Posture Assessment", "TrustSec", "pxGrid"]',
 '["SOC 2", "ISO 27001", "Common Criteria", "FIPS 140-2"]',
 '["TrustSec", "MACsec", "Group-Based Policy", "Threat-Centric NAC"]',
 '["Active Directory", "LDAP", "RADIUS", "TACACS+", "REST API", "pxGrid"]',
 '["TAC Support", "Smart Net", "Professional Services", "Cisco Learning"]',
 '["On-Premises", "Private Cloud", "Hybrid"]',
 '{"max_devices": 100000, "max_policies": 2000, "max_users": 50000}',
 'high', 'leader', 'stable', 8, 8.2),

('aruba-clearpass', 'Aruba ClearPass', 'NAC', 'per_device', 20000, 30, 6000, 10,
 '["Policy Manager", "Guest", "OnBoard", "OnGuard", "Insight", "Exchange", "Universal Profiler"]',
 '["SOC 2", "ISO 27001", "Common Criteria"]',
 '["Dynamic Segmentation", "Device Profiling", "Threat Detection", "Policy Enforcement"]',
 '["Active Directory", "LDAP", "RADIUS", "REST API", "Aruba Central"]',
 '["24/7 Support", "Professional Services", "Training", "Community"]',
 '["On-Premises", "Cloud", "Hybrid"]',
 '{"max_devices": 75000, "max_policies": 1500, "max_users": 25000}',
 'medium', 'challenger', 'stable', 8, 8.0),

('fortinet-fortigate', 'Fortinet FortiGate', 'Firewall', 'per_device', 18000, 20, 4000, 18,
 '["Next-Gen Firewall", "Intrusion Prevention", "Application Control", "Web Filtering", "VPN", "SD-WAN"]',
 '["SOC 2", "ISO 27001", "Common Criteria", "ICSA Labs"]',
 '["FortiGuard Labs", "AI-Powered Security", "SSL Inspection", "Sandboxing"]',
 '["FortiManager", "FortiAnalyzer", "Fabric Connectors", "REST API"]',
 '["FortiCare", "Professional Services", "Training", "Documentation"]',
 '["Physical", "Virtual", "Cloud", "Container"]',
 '{"max_throughput": "100Gbps", "max_sessions": 50000000, "max_policies": 10000}',
 'low', 'leader', 'stable', 9, 8.5),

('palo-alto', 'Palo Alto Networks', 'Firewall', 'per_device', 30000, 40, 10000, 15,
 '["Next-Gen Firewall", "Threat Prevention", "URL Filtering", "WildFire", "GlobalProtect", "Prisma"]',
 '["SOC 2", "ISO 27001", "Common Criteria", "ICSA Labs", "FIPS 140-2"]',
 '["WildFire", "Threat Intelligence", "Machine Learning", "Behavioral Analytics"]',
 '["Panorama", "REST API", "MineMeld", "Cortex", "XSOAR"]',
 '["24/7 Support", "Professional Services", "Training", "Live Community"]',
 '["Physical", "Virtual", "Cloud", "Container"]',
 '{"max_throughput": "200Gbps", "max_sessions": 100000000, "max_policies": 20000}',
 'medium', 'leader', 'stable', 9, 8.8);
